server:
  port: 8080
spring:
  application:
    name: image-ai
  profiles:
    active: @profile@
  ai:
    stabilityai:
      api-key: @stability.ai.apiKey@
    openai:
      api-key: @open.ai.apiKey@